name = "ReactorSimulation"
uuid = "5e355451-1901-4a7b-83c0-1c0b21166627"
authors = ["Caspar Gutsche"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
